SodaMachineRazorUI/Pages/AdminCoinInventory.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SodaMachineLibrary.Logic;
using SodaMachineLibrary.Models;

namespace SodaMachineRazorUI.Pages
{
    [Authorize(Roles = "Admin")]
    public class AdminCoinInventoryModel : PageModel
    {
        private readonly ISodaMachineLogic _sodaMachine;

        [BindProperty(SupportsGet = true)]
        public string OutputText { get; set; }

        [BindProperty(SupportsGet = true)]
        public string ErrorMessage { get; set; }

        public List<CoinModel> Coins{ get; set; }

        [BindProperty]
        public string TotalIncome { get; set; }

        [BindProperty]
        public string CurrentIncome { get; set; }

        [BindProperty]
        public CoinModel Coin { get; set; }

        public AdminCoinInventoryModel(ISodaMachineLogic sodaMachine)
        {
            _sodaMachine = sodaMachine;
        }

        // Used to show coins
        public void OnGet()
        {
            Coins = _sodaMachine.GetCoinInventory().OrderBy(x=>x.Name).ToList();
            CurrentIncome = _sodaMachine.GetCurrentIncome().ToString();
            TotalIncome = _sodaMachine.GetTotalIncome().ToString();
        }

        // Used to deposit coins
        public IActionResult OnPost()
        {
            _sodaMachine.AddToCoinInventory(new List<CoinModel> { Coin });
            
            return RedirectToPage();
        }

        public IActionResult OnPostEmpty() 
        {
            _sodaMachine.EmptyMoneyFromMachine();

            return RedirectToPage();
        }
    }
}

SodaMachineRazorUI/Pages/AdminSodaInventory.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SodaMachineLibrary.Logic;
using SodaMachineLibrary.Models;
using System.Data;

namespace SodaMachineRazorUI.Pages
{
    [Authorize(Roles = "Admin")]
    public class AdminSodaInventoryModel : PageModel
    {
        private readonly ISodaMachineLogic _sodaMachine;

        public List<SodaModel> Sodas { get; set; }
        public List<SelectListItem> SodaOptions { get; set; }
        public List<SelectListItem> SlotOptions { get; set; }

        [BindProperty]
        public string SelectedSoda { get; set; }

        [BindProperty]
        public string SelectedSlot { get; set; }

        public AdminSodaInventoryModel(ISodaMachineLogic sodaMachine)
        {
            _sodaMachine = sodaMachine;
        }

        public void OnGet()
        {
            Sodas = _sodaMachine.GetSodaInventory().OrderBy(x => x.SlotOccupied).ToList();

            SodaOptions = Sodas
                .GroupBy(x => x.Name)
                .Select(x => new SelectListItem
                {
                    Value = x.Key,
                    Text = x.Key
                }).ToList();

            SlotOptions = Sodas
                .GroupBy(x => x.SlotOccupied)
                .Select(x => new SelectListItem
                {
                    Value = x.Key,
                    Text = x.Key
                }).ToList();
        }

        public IActionResult OnPost()
        {
            _sodaMachine.AddToSodaInventory(new List<SodaModel>
            {
                new SodaModel
                {
                    SlotOccupied = SelectedSlot,
                    Name = SelectedSoda
                }
            });

            return RedirectToPage();
        }
    }
}

SodaMachineRazorUI/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SodaMachineRazorUI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SodaMachineRazorUI/Pages/GenerateAdmin.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SodaMachineRazorUI.Pages
{
    [Authorize]
    public class GenerateAdminModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly string _adminRole = "Admin";
        private IConfiguration _config;

        public bool RoleCreated { get; set; }
        public string AdminId { get; set; }

        public GenerateAdminModel(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager, IConfiguration config)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _config = config;
        }
        public async Task OnGet()
        {
            var roleExists = await _roleManager.RoleExistsAsync(_adminRole);
            
            if (roleExists == false)
            {
                await _roleManager.CreateAsync(new IdentityRole(_adminRole));
            }

            string userEmail = _config.GetValue<string>("AdminUser");
            if (string.IsNullOrEmpty(userEmail) != true)
            {
                var user = await _userManager.FindByEmailAsync(userEmail);

                if (user != null)
                {
                    await _userManager.AddToRoleAsync(user, _adminRole);
                    AdminId = user.Id;
                    RoleCreated = true;
                }
            }
        }
    }
}

SodaMachineRazorUI/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SodaMachineRazorUI.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

SodaMachineRazorUI/Pages/MachineIncome.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SodaMachineLibrary.Logic;
using System.Data;

namespace SodaMachineRazorUI.Pages
{
    [Authorize(Roles = "Admin")]

    public class MachineIncome: PageModel
    {
        private readonly ISodaMachineLogic _sodaMachine;

        public decimal CurrentIncome { get; set; }
        public decimal TotalIncome { get; set; }

        public MachineIncome(ISodaMachineLogic sodaMachine)
        {
            _sodaMachine = sodaMachine;
        }

        public void OnGet()
        {
            CurrentIncome = _sodaMachine.GetCurrentIncome();
            TotalIncome = _sodaMachine.GetTotalIncome();
        }

        public IActionResult OnPost()
        {
            _sodaMachine.EmptyMoneyFromMachine();
            return RedirectToPage();
        }
    }
}

SodaMachineRazorUI/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SodaMachineRazorUI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

SodaMachineRazorUI/Pages/SodaMachine.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SodaMachineLibrary.Logic;
using SodaMachineLibrary.Models;
using System.Security.Claims;

namespace SodaMachineRazorUI.Pages
{
    [Authorize]
    public class SodaMachineModel : PageModel
    {
        private readonly ISodaMachineLogic _sodaMachine;

        public decimal SodaPrice { get; set; }
        public decimal DepositedAmount { get; set; }
        public List<SodaModel> SodaOptions { get; set; }

        [BindProperty]
        public decimal Deposit { get; set; }

        [BindProperty]
        public SodaModel SelectedSoda { get; set; }


        public string UserId 
        { 
            get 
            {
                return User.FindFirstValue(ClaimTypes.NameIdentifier);
            }
        }

        [BindProperty(SupportsGet = true)]
        public string OutputText { get; set; }

        [BindProperty(SupportsGet = true)]
        public string ErrorMessage { get; set; }

        public SodaMachineModel(ISodaMachineLogic sodaMachine)
        {
            _sodaMachine = sodaMachine;
        }

        public void OnGet()
        {
            SodaPrice = _sodaMachine.GetSodaPrice();
            DepositedAmount = _sodaMachine.GetMoneyInsertedTotal(UserId);
            SodaOptions = _sodaMachine.ListTypesOfSoda();
        }

        // Used for depositing coins
        public IActionResult OnPost()
        {
            if (Deposit > 0)
            {
                _sodaMachine.MoneyInserted(UserId, Deposit);
            }

            return RedirectToPage();
        }

        // Used for requesting soda
        public IActionResult OnPostSoda()
        {
            var results = _sodaMachine.RequestSoda(SelectedSoda, UserId);
            OutputText = "";

            // Handle the response
            if (results.errorMessage.Length > 0)
            {
                ErrorMessage = results.errorMessage;
            }
            else
            {
                OutputText = $"Here is your {results.soda.Name}";

                if (results.change.Count > 0)
                {
                    OutputText += "<br><br>Here is your change:<br>";
                    results.change.ForEach(x => OutputText += $"{x.Name}<br>");
                }
                else
                {
                    OutputText += "<br><br>You used exact change so there is no change to refund.";
                }
            }

            return RedirectToPage(new { ErrorMessage, OutputText });
        }

        // Used for cancelling our deposit
        public IActionResult OnPostCancel()
        {
            DepositedAmount = _sodaMachine.GetMoneyInsertedTotal(UserId);
            _sodaMachine.IssueFullRefund(UserId);

            OutputText = $"You have been refunded {String.Format("{0:C}", DepositedAmount)}";

            return RedirectToPage(new { OutputText });
        }
    }
}

SodaMachineRazorUI/Pages/AdminCoinInventory.cshtml
@page
@model SodaMachineRazorUI.Pages.AdminCoinInventoryModel

@if (String.IsNullOrWhiteSpace(Model.ErrorMessage) == false)
{
    <p class="text-danger">
        @Model.ErrorMessage
    </p>
}

<div class="row">
    <div class="col-sm-8">
    <h3>Coins in Inventory</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Coin</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Value</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var coin in Model.Coins.GroupBy(x=>x.Name).Select(y =>
                new {
                    name = y.Key,
                    quantity = y.Count(),
                    type = y.First().Amount
                    }).ToList())
                {
                    <tr>
                        <td>@coin.name</td>
                        <td>@coin.quantity</td>
                        <td>@coin.type</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-sm-4">
        @Html.Raw(Model.OutputText)
    </div>
</div>
<br />
<div class="row">
    <div class="col-sm-4">
        <h3>Deposit Coins</h3>
        <div class="btn-group" role="group">
            <form method="post">
                <input type="hidden" asp-for="Coin.Name" value="Nickle" />
                <input type="hidden" asp-for="Coin.Amount" value="0.05" />
                <button type="submit" class="btn btn-primary">@String.Format("{0:C}", 0.05)</button>
            </form>
            <form method="post">
                <input type="hidden" asp-for="Coin.Name" value="Dime" />
                <input type="hidden" asp-for="Coin.Amount" value="0.1" />
                <button type="submit" class="btn btn-primary">@String.Format("{0:C}", 0.10)</button>
            </form>
            <form method="post">
                <input type="hidden" asp-for="Coin.Name" value="Quarter" />
                <input type="hidden" asp-for="Coin.Amount" value="0.25" />
                <button type="submit" class="btn btn-primary">@String.Format("{0:C}", 0.25)</button>
            </form>
        </div>
    </div>
    <div class="col-sm-8">
        <h4>Total income: @Model.TotalIncome</h4>
        <h4>Cash on hand: @Model.CurrentIncome</h4>
        <form method="post" asp-page-handler="Empty">
            <button type="submit" class="btn btn-warning">Empty Coins</button>
        </form>
    </div>
</div>

SodaMachineRazorUI/Pages/AdminSodaInventory.cshtml
@page
@model SodaMachineRazorUI.Pages.AdminSodaInventoryModel
@{
    ViewData["Title"] = "SodaInventory";
}

<h1>Soda Inventory</h1>

<div class="row">
    <div class="col-6">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Slot</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var soda in Model.Sodas)
                {
                    <tr>
                        <td>@soda.Name</td>
                        <td>@soda.SlotOccupied</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-6">
        <form method="post">
            <div class="form-group">
                <label for="selectedSoda">Select A Soda</label>
                <select id="selectedSoda" asp-for="@Model.SelectedSoda"
                        asp-items="@Model.SodaOptions" class="form-control"></select>
            </div>
            <div class="form-group">
                <label for="selectedSlot">Select A Slot</label>
                <select id="selectedSlot" asp-for="@Model.SelectedSlot"
                        asp-items="@Model.SlotOptions" class="form-control"></select>
            </div>
            <button type="submit" class="btn btn-primary">Add Soda to Inventory</button>
        </form>
    </div>
</div>

SodaMachineRazorUI/Pages/GenerateAdmin.cshtml
@page
@model SodaMachineRazorUI.Pages.GenerateAdminModel
@{
    ViewData["Title"] = "GenerateAdmin";
}

<h1>Generate Admin</h1>
<br />

<h3>Role created: @Model.RoleCreated</h3>
<h3>Admin id: @Model.AdminId</h3>

SodaMachineRazorUI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SodaMachineRazorUI/Pages/MachineIncome.cshtml
@page
@model SodaMachineRazorUI.Pages.MachineIncome
@{
    ViewData["Title"] = "MachineIncome";
}

<h1>Machine Income</h1>
<div class="h3">
    <strong>Current Income: </strong>@String.Format("{0:C}", Model.CurrentIncome)
</div>
<div class="h3">
    <strong>Total Income: </strong>@String.Format("{0:C}", Model.TotalIncome)
</div>
<div>
    <form method="post">
        <button type="submit" class="btn btn-primary">Withdraw Current Income</button>
    </form>
</div>

SodaMachineRazorUI/Pages/SodaMachine.cshtml
@page
@using SodaMachineLibrary.Models;
@model SodaMachineRazorUI.Pages.SodaMachineModel
@{
    ViewData["Title"] = "SodaMachine";
}
<!-- https://getbootstrap.com -->

<h1>Soda Machine</h1>
<h5>Soda Price: @String.Format("{0:C}", Model.SodaPrice)</h5>
<h5>Deposited Amount: @String.Format("{0:C}", Model.DepositedAmount)</h5>

@if (String.IsNullOrWhiteSpace(Model.ErrorMessage) == false)
{
    <p class="text-danger">
        @Model.ErrorMessage
    </p>
}

<div class="row">
    <div class="col-sm-8">
        @foreach (var soda in Model.SodaOptions)
        {
            <div class="row">
                <div class="col-sm-8 soda-tab bg-secondary text-white">
                    @soda.Name
                </div>
                <div class="col-sm-4">
                    <form method="post" asp-page-handler="Soda">
                        <input type="hidden" asp-for="UserId" />
                        <input type="hidden" asp-for="SelectedSoda.Name" value="@soda.Name" />
                        <input type="hidden" asp-for="SelectedSoda.SlotOccupied" value="@soda.SlotOccupied" />
                        <button type="submit" class="btn btn-primary btn-soda">Buy</button>
                    </form>
                </div>
            </div>
        }
    </div>
    <div class="col-sm-4">
        @Html.Raw(Model.OutputText)
    </div>
</div>

<div class="row">
    <div class="col-sm-4">
        <h3>Deposit Coins</h3>
        <div class="btn-group" role="group">
            <form method="post">
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="Deposit" value="0.05" />
                <button type="submit" class="btn btn-primary">@String.Format("{0:C}", 0.05)</button>
            </form>
            <form method="post">
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="Deposit" value="0.10" />
                <button type="submit" class="btn btn-primary">@String.Format("{0:C}", 0.10)</button>
            </form>
            <form method="post">
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="Deposit" value="0.25" />
                <button type="submit" class="btn btn-primary">@String.Format("{0:C}", 0.25)</button>
            </form>
        </div>
    </div>
    <div class="col-sm-4">
        <h3>Cancel Transaction</h3>
        <form method="post" asp-page-handler="Cancel">
            <input type="hidden" asp-for="UserId" />
            <button type="submit" class="btn btn-warning">Eject Money</button>
        </form>
    </div>
</div>